export const BuilderMethods = {
    GETTERS: {
        GET_BOARD: "GET_BOARD",
        GET_BOARD_MODE: "GET_BOARD_MODE",
        GET_SELECTED: "GET_SELECTED",
        GET_AVAILABLE_EXPRESSIONS: "GET_AVAILABLE_EXPRESSIONS",
        GET_EMITTERS: "GET_EMITTERS"
    },
    MUTATIONS: {
        SET_CONTAINER: "SET_CONTAINER",
        SET_SELECTED: "SET_SELECTED",
        SET_PROPERTY: "SET_PROPERTY",
        SET_AVAILABLE_EXPRESSIONS: "SET_AVAILABLE_EXPRESSIONS",
        SET_CREATED_NODES: "SET_CREATED_NODES",
        SET_CREATED_LABELS: "SET_CREATED_LABELS",
        SET_EMITTERS: "SET_EMITTERS"
    },
    ACTIONS: {
        START_BOARD: "START_BOARD",
        CREATE_NODE: "CREATE_NODE",
        CHANGE_MODE: "CHANGE_MODE",
        SELECT_NODE: "SELECT_NODE",
        DELETE_COMPONENT: "DELETE_COMPONENT",
        MOVE_NODE: "MOVE_NODE",
        CHANGE_PROPERTY: "CHANGE_PROPERTY",
        CREATE_PATH: "CREATE_PATH",
        SAVE_EXPERIMENT: "SAVE_EXPERIMENT",
        LOAD_EXPERIMENT: "LOAD_EXPERIMENT",
    },
};
