export enum ModelerEvents {
    SELECTED_PATH = "SELECTED_PATH",
    SELECTED_NODE = "SELECTED_NODE",
    DEFAULT_MODE = "DEFAULT_MODE",
    DELETING_MODE = "DELETING_MODE",
    CREATING_MODE = "CREATING_MODE",
    PATH_CREATED = "CREATING_MODE",
    DELETED_COMPONENT = "DELETED_COMPONENT",
    NODE_MOVED = "NODE_MOVED"
}