export const SimulationMethods = {
    GETTERS: {
        GET_SIMULATOR_STATUS: "GET_SIMULATOR_STATUS",
        GET_SIMULATION_STATS: "GET_SIMULATION_STATS",
        GET_SIMULATION_PARAMS: "GET_SIMULATION_PARAMS",
    },
    MUTATIONS: {
        SET_SIMULATOR_STATUS: "SET_SIMULATOR_STATUS",
        SET_SIMULATION_STATS: "SET_SIMULATION_STATS",
    },
    ACTIONS: {

    }
}