export const SimulationMethods = {
    GETTERS: {
        GET_SIMULATOR_STATUS: "GET_SIMULATOR_STATUS",
        GET_SIMULATION_STATS: "GET_SIMULATION_STATS",
        GET_SIMULATION_PARAMS: "GET_SIMULATION_PARAMS",
    },
    MUTATIONS: {
        SET_SIMULATOR_STATUS: "SET_SIMULATOR_STATUS",
        SET_SIMULATION_STATS: "SET_SIMULATION_STATS",
    },
    ACTIONS: {
        START_SIMULATION: "START_SIMULATION",
        NEXT_STEP: "NEXT_STEP",
        FAST_FORWARD: "FAST_FORWARD",
        STOP_SIMULATION: "STOP_SIMULATION",
        PAUSE_SIMULATION: "PAUSE_SIMULATION",
        SOCKET_SIMULATION_STATUS: "SOCKET_SIMULATION_STATUS",
        SOCKET_OUTPUT_SAVED: "SOCKET_OUTPUT_SAVED",
        SOCKET_SIMULATION_FINISHED: "SOCKET_SIMULATION_FINISHED"
    }
}